spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Qianmi123
    url: jdbc:mysql://39.106.70.187:3306/sanjing?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null




